#ifndef SG_MATERIAL_TYPES_H_INCLUDED
#define SG_MATERIAL_TYPES_H_INCLUDED

namespace sg
{
enum SG_MATERIAL_TYPE
{
    SGMT_STATIC_MESH,
    SGMT_LINE,
    SGMT_SPRITE
};
}

#endif // SG_MATERIAL_TYPES_H_INCLUDED
