#ifndef SG_MATERIAL_TYPES_H_INCLUDED
#define SG_MATERIAL_TYPES_H_INCLUDED

namespace sg
{
enum SG_MATERIAL_TYPE
{
    SGM_STATIC_MESH,
    SGM_LINE,
    SGM_POINT_SPRITE,
    SGM_VSM_FIRST_PASS,
    SGM_VSM_FINAL_PASS,
    SGM_TEXTURE_FILTER,
};
}

#endif // SG_MATERIAL_TYPES_H_INCLUDED
